
service: x-word-getter
useDotenv: true
plugins:
  - serverless-dotenv-plugin

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./

  iam:
    role:
      name: custom-role-name
      statements:
        - Effect: 'Allow'
          Resource: 'arn:aws:s3:::puzzle-pdf-bucket/*'
          Action: 's3:PutObject'

functions:
  PuzzleToS3Cron:
    memorySize: 2048
    image:
      name: appimage
    events:
      - schedule: cron(30 6 ? * MON,WED,FRI *)
    timeout: 90 # in seconds
  TestFunc:
    image:
      name: appimage
      command:
        - dist/handler2.Handler


# The "Resources" your "Functions" use.  Raw AWS CloudFormation goes in here.
resources:
  Resources:
    puzzlePdfBucket:
      Type: 'AWS::S3::Bucket'
      DeletionPolicy: Retain
      Properties:
        BucketName: puzzle-pdf-bucket