
service: x-word-getter
useDotenv: true
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
package:
  individually: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  PuzzleToS3Cron:
    handler: src/handler/PuzzleToS3Cron.Handler
    events:
      - schedule: cron(30 6 ? * MON,WED,FRI *)
    timeout: 90 # in seconds


