
service: x-word-getter
useDotenv: true
plugins:
  - serverless-dotenv-plugin

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./

functions:
  PuzzleToS3Cron:
    image:
      name: appimage
    # handler: dist/handler/PuzzleToS3Cron.Handler
    events:
      - schedule: cron(30 6 ? * MON,WED,FRI *)
    timeout: 90 # in seconds


